controller:
  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
      prometheus.io/port : "10254"
      prometheus.io/scrape: "true"
  
  metrics:
    enabled: true
  
    