name : Destroy
on: 
  workflow_dispatch:
jobs:
  destroy:
    runs-on: [self-hosted, linux, x64]
    steps:
      - uses: actions/checkout@v4
      - name : helm  destroy
        run : |
          make dev-destroy vault_token=${vault_token}
        working-directory: ./helm-charts
        env:
          vault_token: ${{ secrets.VAULT_TOKEN }}
      - name: terraform infra destroy
        run : |
          make dev-destroy vault_token=${vault_token}
        working-directory : ./
        env:
          vault_token: ${{ secrets.VAULT_TOKEN }}